### ISSUE TITLE
Double transpiled `DESCRIBE` queries on `cursor.description`

### ISSUE THREAD

**Issue by seruman** [tekumara/fakesnow#61]
On any *non-cmd* queries, `_last_sql` on cursor is set to transpiled DuckDB query;
https://github.com/tekumara/fakesnow/blob/b7be898eb4cc19a4d083195a317044ec8ca360c0/fakesnow/fakes.py#L320

On `.description` access, *transpiled* `_last_query` is executed with `DESCRIBE <..>`, thus gets double transpiled here;
https://github.com/tekumara/fakesnow/blob/b7be898eb4cc19a4d083195a317044ec8ca360c0/fakesnow/fakes.py#L112-L118

```
SELECT DATE_DIFF('DAY', CAST('2023-04-02' AS DATE), CAST('2023-04-05' AS DATE));
DESCRIBE SELECT DATE_DIFF('CAST('2023-04-05' AS DATE)', CAST('2023-04-02' AS DATE), 'DAY');
```

----

```python
import fakesnow
import snowflake.connector

q = """SELECT DATEDIFF( DAY, '2023-04-02'::DATE, '2023-04-05'::DATE)"""

with fakesnow.patch():
    conn = snowflake.connector.connect()
    with conn.cursor() as cur:
        cur.execute(q)
        rows = cur.fetchall()
        desc = cur.description

        print(rows)
        print(desc)
```

```
python-3.11 ; FAKESNOW_DEBUG=true python3 main.py
SELECT DATE_DIFF('DAY', CAST('2023-04-02' AS DATE), CAST('2023-04-05' AS DATE));
DESCRIBE SELECT DATE_DIFF('CAST('2023-04-05' AS DATE)', CAST('2023-04-02' AS DATE), 'DAY');
Traceback (most recent call last):
  File "/private/tmp/mm/main.py", line 11, in <module>
    desc = cur.description
           ^^^^^^^^^^^^^^^
  File "/private/tmp/mm/.direnv/python-3.11/lib/python3.11/site-packages/fakesnow/fakes.py", line 115, in description
    cur.execute(f"DESCRIBE {self._last_sql}", self._last_params)
  File "/private/tmp/mm/.direnv/python-3.11/lib/python3.11/site-packages/fakesnow/fakes.py", line 129, in execute
    return self._execute(command, params, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/mm/.direnv/python-3.11/lib/python3.11/site-packages/fakesnow/fakes.py", line 219, in _execute
    self._duck_conn.execute(sql, params)
duckdb.duckdb.ParserException: Parser Error: syntax error at or near "2023"
```

* Python: 3.11.5
* sqlglot: 21.2.1
* fakesnow: 0.9.6

-------------

I did a quick hack to walk around this but not sure if this was on on purpose and I'm not missing anything;

```diff
     def _execute(
         self,
         command: str,
         params: Sequence[Any] | dict[Any, Any] | None = None,
+        _describe_only: bool = False,
         *args: Any,
         **kwargs: Any,
     ) -> FakeSnowflakeCursor:
# ...
         try:
-            self._duck_conn.execute(sql, params)
+            q = sql if not _describe_only else command
+            self._duck_conn.execute(q, params)
         except duckdb.BinderException as e:

```

**Comment by tekumara** [comment]
Ah good catch! This wasn't intentional and your hack does the job well. What I'll probably do though is take this as an opportunity to do some refactoring.
